spring:
  application:
    name: user-service

  # Configuration will be loaded from Config Server
  # Local configuration for development/testing only
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}"

# Actuator Configuration for Prometheus Metrics
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: user-service
      environment: production

# Logging Configuration
logging:
  level:
    com.yushan.user: DEBUG
    org.springframework.cloud: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"