-- Insert 20 additional authors
INSERT INTO users (
    uuid, email, username, hash_password, avatar_url,
    profile_detail, birthday, gender, is_admin, is_author,
    status, create_time, update_time, last_login, last_active
) VALUES
-- Author 1
(gen_random_uuid(), 'john.smith@yushan.com', 'johnsmith', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Fantasy and sci-fi author with 10+ years experience', '1985-03-15', 0, false, true, 1, CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
-- Author 2
(gen_random_uuid(), 'sarah.johnson@yushan.com', 'sarahjohnson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Romance novelist specializing in contemporary love stories', '1988-07-22', 1, false, true, 1, CURRENT_TIMESTAMP - INTERVAL '55 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
-- Author 3
(gen_random_uuid(), 'mike.chen@yushan.com', 'mikechen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Martial arts and cultivation expert', '1982-11-08', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '50 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '20 minutes'),
-- Author 4
(gen_random_uuid(), 'emma.wilson@yushan.com', 'emmawilson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Urban fantasy and paranormal romance writer', '1990-04-12', 1, false, true, 1, CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '4 hours', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
-- Author 5
(gen_random_uuid(), 'alex.rodriguez@yushan.com', 'alexrodriguez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G','user_male.png', 'Sci-fi and space opera specialist', '1987-09-18', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '45 minutes'),
-- Author 6
(gen_random_uuid(), 'lisa.brown@yushan.com', 'lisabrown', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Historical fiction and period drama author', '1984-12-03', 1, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '35 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
-- Author 7
(gen_random_uuid(), 'david.kim@yushan.com', 'davidkim', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Mystery and thriller novelist', '1989-06-25', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
-- Author 8
(gen_random_uuid(), 'jessica.taylor@yushan.com', 'jessicataylor', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Young adult fantasy and adventure writer', '1992-01-14', 1, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
-- Author 9
(gen_random_uuid(), 'robert.garcia@yushan.com', 'robertgarcia', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G',  'user_male.png', 'Military fiction and war stories expert', '1981-08-30', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '25 minutes'),
-- Author 10
(gen_random_uuid(), 'amanda.davis@yushan.com', 'amandadavis', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G','user_female.png', 'Contemporary romance and womens fiction', '1986-05-17', 1, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
-- Author 11
(gen_random_uuid(), 'kevin.lee@yushan.com', 'kevinlee', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Cyberpunk and dystopian fiction writer', '1983-10-09', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '40 minutes'),
-- Author 12
(gen_random_uuid(), 'michelle.white@yushan.com', 'michellewhite', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Paranormal romance and supernatural fiction', '1988-02-28', 1, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '4 hours', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
-- Author 13
(gen_random_uuid(), 'james.miller@yushan.com', 'jamesmiller', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Epic fantasy and high fantasy specialist', '1980-12-11', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
-- Author 14
(gen_random_uuid(), 'jennifer.anderson@yushan.com', 'jenniferanderson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Slice of life and coming of age stories', '1991-07-06', 1, false, true, 1, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
-- Author 15
(gen_random_uuid(), 'william.thomas@yushan.com', 'williamthomas', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Horror and psychological thriller author', '1985-04-23', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
-- Author 16
(gen_random_uuid(), 'sophia.martinez@yushan.com', 'sophiamartinez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'LGBTQ+ romance and diverse fiction', '1987-11-19', 1, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
-- Author 17
(gen_random_uuid(), 'daniel.jackson@yushan.com', 'danieljackson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Adventure and exploration fiction', '1984-03-07', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '12 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
-- Author 18
(gen_random_uuid(), 'olivia.harris@yushan.com', 'oliviaharris', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Literary fiction and character-driven stories', '1989-09-15', 1, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '6 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '45 minutes'),
-- Author 19
(gen_random_uuid(), 'christopher.moore@yushan.com', 'christophermoore', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Comedy and satirical fiction', '1982-06-12', 0, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
-- Author 20
(gen_random_uuid(), 'natalie.clark@yushan.com', 'natalieclark', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Magical realism and surreal fiction', '1986-08-04', 1, false, true, 1,  CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 minutes', CURRENT_TIMESTAMP - INTERVAL '5 minutes');

INSERT INTO users (
    uuid, email, username, hash_password, avatar_url,
    profile_detail, birthday, gender, is_admin, is_author,
    status, create_time, update_time, last_login, last_active
) VALUES
      (gen_random_uuid(), 'alice.johnson@yushan.com', 'alicejohnson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Fantasy enthusiast and avid reader', '1995-03-15', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'bob.smith@yushan.com', 'bobsmith', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Sci-fi lover and technology enthusiast', '1992-07-22', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
      (gen_random_uuid(), 'carol.williams@yushan.com', 'carolwilliams', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Romance reader and book club member', '1998-11-08', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '35 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'david.brown@yushan.com', 'davidbrown', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Martial arts fan and action lover', '1990-04-12', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '4 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'eve.davis@yushan.com', 'evedavis', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Urban fantasy reader and night owl', '1993-09-18', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'frank.miller@yushan.com', 'frankmiller', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Historical fiction enthusiast', '1987-12-03', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'grace.wilson@yushan.com', 'gracewilson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Young adult fiction lover', '1996-06-25', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'henry.taylor@yushan.com', 'henrytaylor', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Mystery and thriller reader', '1991-01-14', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'iris.garcia@yushan.com', 'irisgarcia', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Paranormal romance fan', '1994-08-30', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '45 minutes'),
      (gen_random_uuid(), 'jack.anderson@yushan.com', 'jackanderson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Military fiction enthusiast', '1989-05-17', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
      (gen_random_uuid(), 'karen.lee@yushan.com', 'karenlee', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Contemporary romance reader', '1997-10-09', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
      (gen_random_uuid(), 'leo.white@yushan.com', 'leowhite', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Cyberpunk and dystopian fiction fan', '1992-02-28', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'mary.martinez@yushan.com', 'marymartinez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Epic fantasy reader', '1995-12-11', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'nick.thomas@yushan.com', 'nickthomas', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Horror and thriller enthusiast', '1990-07-06', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '12 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'olivia.jackson@yushan.com', 'oliviajackson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Slice of life and drama reader', '1993-04-23', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '6 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 hours', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'peter.harris@yushan.com', 'peterharris', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Adventure and exploration fiction fan', '1988-11-19', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'quinn.moore@yushan.com', 'quinnmoore', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Literary fiction and character-driven stories', '1991-03-07', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
      (gen_random_uuid(), 'ryan.clark@yushan.com', 'ryanclark', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Comedy and satirical fiction reader', '1994-09-15', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 minutes', CURRENT_TIMESTAMP - INTERVAL '5 minutes'),
      (gen_random_uuid(), 'sophia.lewis@yushan.com', 'sophialewis', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Magical realism and surreal fiction lover', '1996-06-12', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '15 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '10 minutes', CURRENT_TIMESTAMP - INTERVAL '2 minutes'),
      (gen_random_uuid(), 'tom.walker@yushan.com', 'tomwalker', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Science fiction and space opera fan', '1989-08-04', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 minutes', CURRENT_TIMESTAMP - INTERVAL '1 minute'),
      (gen_random_uuid(), 'una.martin@yushan.com', 'unamartin', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Fantasy romance and adventure reader', '1992-11-30', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '2 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 minute', CURRENT_TIMESTAMP - INTERVAL '30 seconds'),
      (gen_random_uuid(), 'victor.nguyen@yushan.com', 'victornguyen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Martial arts and cultivation enthusiast', '1987-05-14', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 minute', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 seconds', CURRENT_TIMESTAMP - INTERVAL '10 seconds'),
      (gen_random_uuid(), 'wendy.king@yushan.com', 'wendyking', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Urban fantasy and paranormal romance lover', '1994-09-22', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 seconds', CURRENT_TIMESTAMP - INTERVAL '5 seconds'),
      (gen_random_uuid(), 'xavier.lopez@yushan.com', 'xavierlopez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Historical fiction and period drama fan', '1986-12-08', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '15 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '10 seconds', CURRENT_TIMESTAMP - INTERVAL '3 seconds'),
      (gen_random_uuid(), 'yara.singh@yushan.com', 'yarasingh', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Contemporary romance and womens fiction reader', '1991-03-18', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '10 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '5 seconds', CURRENT_TIMESTAMP - INTERVAL '2 seconds'),
      (gen_random_uuid(), 'zachary.wright@yushan.com', 'zacharywright', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Mystery and thriller enthusiast', '1989-07-25', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 seconds', CURRENT_TIMESTAMP - INTERVAL '1 second'),
      (gen_random_uuid(), 'alice.johnson@gmail.com', 'alicejohnson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Book lover and avid reader', '1995-03-15', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'bob.smith@yahoo.com', 'bobsmith', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Fantasy and sci-fi enthusiast', '1988-07-22', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'carol.williams@hotmail.com', 'carolwilliams', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Romance novel reader', '1992-11-08', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '35 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
      (gen_random_uuid(), 'david.brown@outlook.com', 'davidbrown', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Mystery and thriller fan', '1987-04-12', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '45 minutes'),
      (gen_random_uuid(), 'emma.davis@gmail.com', 'emmadavis', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Historical fiction lover', '1990-09-18', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'frank.miller@yahoo.com', 'frankmiller', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Adventure and action reader', '1985-12-03', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
      (gen_random_uuid(), 'grace.wilson@hotmail.com', 'gracewilson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Young adult fiction reader', '1993-06-25', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
      (gen_random_uuid(), 'henry.moore@outlook.com', 'henrymoore', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Science fiction enthusiast', '1989-01-14', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'iris.taylor@gmail.com', 'iristaylor', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Literary fiction reader', '1991-08-30', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'jack.anderson@yahoo.com', 'jackanderson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Horror and supernatural fan', '1986-05-17', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '20 minutes'),
      (gen_random_uuid(), 'karen.thomas@hotmail.com', 'karenthomas', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Contemporary romance reader', '1994-10-09', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'leo.jackson@outlook.com', 'leojackson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Military and war fiction', '1983-02-28', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '25 minutes'),
      (gen_random_uuid(), 'mary.white@gmail.com', 'marywhite', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Urban fantasy lover', '1996-12-11', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '40 minutes'),
      (gen_random_uuid(), 'nick.harris@yahoo.com', 'nickharris', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Cyberpunk and dystopian reader', '1988-07-06', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '12 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '10 minutes'),
      (gen_random_uuid(), 'olivia.martin@hotmail.com', 'oliviamartin', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Paranormal romance reader', '1992-04-23', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '6 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'paul.garcia@outlook.com', 'paulgarcia', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Epic fantasy enthusiast', '1987-11-19', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '5 minutes'),
      (gen_random_uuid(), 'quinn.lee@gmail.com', 'quinnlee', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Slice of life stories', '1995-03-07', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
      (gen_random_uuid(), 'ryan.clark@yahoo.com', 'ryanclark', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Psychological thriller fan', '1989-09-15', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 minutes'),
      (gen_random_uuid(), 'sophia.rodriguez@hotmail.com', 'sophiarodriguez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'LGBTQ+ fiction reader', '1993-06-25', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '15 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 minute'),
      (gen_random_uuid(), 'tom.walker@outlook.com', 'tomwalker', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Adventure and exploration', '1985-01-14', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 seconds'),
      (gen_random_uuid(), 'anna.kim@gmail.com', 'annakim', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Korean drama and romance reader', '1994-05-20', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '50 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'ben.chen@yahoo.com', 'benchen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Martial arts and cultivation', '1987-08-15', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '48 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '45 minutes'),
      (gen_random_uuid(), 'carla.silva@hotmail.com', 'carlasilva', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Latin American literature', '1991-12-03', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '45 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
      (gen_random_uuid(), 'diego.rodriguez@outlook.com', 'diegorodriguez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Spanish literature enthusiast', '1989-03-18', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '42 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'elena.petrov@gmail.com', 'elenapetrov', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Russian literature reader', '1993-07-25', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '40 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'frank.zhang@yahoo.com', 'frankzhang', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Chinese web novels', '1986-11-12', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '38 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '20 minutes'),
      (gen_random_uuid(), 'grace.nguyen@hotmail.com', 'gracenguyen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Vietnamese literature', '1992-04-08', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '35 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'harry.singh@outlook.com', 'harrysingh', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Indian mythology and fantasy', '1988-09-30', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '32 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
      (gen_random_uuid(), 'isabella.torres@gmail.com', 'isabellatorres', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Mexican literature', '1995-01-22', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
      (gen_random_uuid(), 'james.oconnor@yahoo.com', 'jamesoconnor', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Irish literature', '1984-06-14', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '28 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '25 minutes'),
      (gen_random_uuid(), 'kate.murphy@hotmail.com', 'katemurphy', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Australian literature', '1990-10-07', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '25 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'liam.oconnell@outlook.com', 'liamoconnell', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Celtic mythology', '1987-02-19', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '22 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '10 minutes'),
      (gen_random_uuid(), 'maya.patel@gmail.com', 'mayapatel', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'South Asian literature', '1993-05-26', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '20 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'nathan.wong@yahoo.com', 'nathanwong', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Hong Kong literature', '1989-08-11', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '18 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '35 minutes'),
      (gen_random_uuid(), 'olivia.kim@hotmail.com', 'oliviakim', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Korean web novels', '1996-12-28', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '15 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '2 hours'),
      (gen_random_uuid(), 'peter.anderson@outlook.com', 'peteranderson', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Scandinavian noir', '1985-03-05', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '12 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '5 minutes'),
      (gen_random_uuid(), 'quinn.martinez@gmail.com', 'quinnmartinez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Latinx literature', '1991-07-17', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '10 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'robert.kim@yahoo.com', 'robertkim', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Korean fantasy', '1988-11-23', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '8 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'sarah.johnson@hotmail.com', 'sarahjohnson2', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'British literature', '1994-04-16', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'thomas.lee@outlook.com', 'thomaslee', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Chinese literature', '1986-09-02', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '3 days', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 minutes'),
      (gen_random_uuid(), 'una.oconnor@gmail.com', 'unaoconnor', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Irish folklore', '1992-01-13', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '45 minutes'),
      (gen_random_uuid(), 'victor.nguyen@yahoo.com', 'victornguyen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Vietnamese fantasy', '1989-06-09', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '12 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '10 minutes'),
      (gen_random_uuid(), 'wendy.chen@hotmail.com', 'wendychen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Chinese romance', '1995-10-31', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '6 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 days', CURRENT_TIMESTAMP - INTERVAL '1 hour'),
      (gen_random_uuid(), 'xavier.rodriguez@outlook.com', 'xavierrodriguez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Spanish fantasy', '1987-03-27', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '3 hours', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '5 minutes'),
      (gen_random_uuid(), 'yuki.tanaka@gmail.com', 'yukitanaka', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Japanese literature', '1993-08-14', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 hour', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 minutes'),
      (gen_random_uuid(), 'zachary.wong@yahoo.com', 'zacharywong', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Cantonese literature', '1988-12-01', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '2 minutes'),
      (gen_random_uuid(), 'alexandra.smith@hotmail.com', 'alexandrasmith', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Canadian literature', '1994-05-18', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '15 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 minute'),
      (gen_random_uuid(), 'brandon.kim@outlook.com', 'brandonkim', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Korean sci-fi', '1986-10-25', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '30 seconds'),
      (gen_random_uuid(), 'catherine.davis@gmail.com', 'catherinedavis', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Australian romance', '1991-02-12', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '2 minutes', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '15 seconds'),
      (gen_random_uuid(), 'daniel.patel@yahoo.com', 'danielpatel', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Indian sci-fi', '1989-07-08', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 minute', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '5 seconds'),
      (gen_random_uuid(), 'elena.garcia@hotmail.com', 'elenagarcia', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Mexican fantasy', '1996-11-21', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '30 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 second'),
      (gen_random_uuid(), 'felix.lee@outlook.com', 'felixlee', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Chinese cultivation', '1987-04-03', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '10 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 second'),
      (gen_random_uuid(), 'gina.martinez@gmail.com', 'ginamartinez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Latinx romance', '1993-09-16', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '5 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 second'),
      (gen_random_uuid(), 'hugo.silva@yahoo.com', 'hugosilva', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Brazilian literature', '1985-01-29', 0, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '2 seconds', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 second'),
      (gen_random_uuid(), 'iris.wang@hotmail.com', 'iriswang', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Chinese romance', '1992-06-05', 1, false, false, 1, CURRENT_TIMESTAMP - INTERVAL '1 second', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 second'),
      (gen_random_uuid(), 'jason.kim@outlook.com', 'jasonkim', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Korean thriller', '1988-12-17', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'kelly.zhang@gmail.com', 'kellyzhang', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Chinese fantasy', '1995-03-24', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'liam.oconnell@yahoo.com', 'liamoconnell2', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Irish mythology', '1984-08-11', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'maya.singh@hotmail.com', 'mayasingh', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Indian romance', '1990-11-28', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'nathan.torres@outlook.com', 'nathantorres', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Mexican thriller', '1987-05-15', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'olivia.nguyen@gmail.com', 'olivianguyen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Vietnamese romance', '1993-10-02', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'peter.chen@yahoo.com', 'peterchen', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Chinese sci-fi', '1986-01-19', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'quinn.murphy@hotmail.com', 'quinnmurphy', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Irish romance', '1994-07-06', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'ryan.kim@outlook.com', 'ryankim', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Korean fantasy', '1989-12-13', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'sophia.lee@gmail.com', 'sophialee', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Chinese romance', '1991-04-20', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'thomas.rodriguez@yahoo.com', 'thomasrodriguez', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Spanish thriller', '1985-09-27', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'una.patel@hotmail.com', 'unapatel', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Indian fantasy', '1992-02-14', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'victor.wong@outlook.com', 'victorwong', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Hong Kong thriller', '1988-06-01', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'wendy.silva@gmail.com', 'wendysilva', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Brazilian romance', '1995-11-18', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'xavier.garcia@yahoo.com', 'xaviergarcia', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Mexican fantasy', '1987-03-25', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'yuki.tanaka@hotmail.com', 'yukitanaka2', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_female.png', 'Japanese romance', '1993-08-12', 1, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP),
      (gen_random_uuid(), 'zachary.lee@outlook.com', 'zacharylee', '$2a$10$VXLDKUp3hDHJn9a17ZNsI.ZJZi.bWjwqLrkjEIug4pHGt1OsUGR5G', 'user_male.png', 'Korean thriller', '1989-12-29', 0, false, false, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP - INTERVAL '1 day', CURRENT_TIMESTAMP);

-- 2. Update user status distribution
-- Set 50 users to status 0, rest random between 1 and 2
WITH user_updates AS (
    SELECT
        uuid,
        ROW_NUMBER() OVER (ORDER BY create_time) as rn
    FROM users
    WHERE is_admin = false
)
UPDATE users
SET status = CASE
                 WHEN uu.rn <= 50 THEN 0
                 ELSE FLOOR(random() * 2) + 1
    END
    FROM user_updates uu
WHERE users.uuid = uu.uuid;

-- 3. Create library for each user
INSERT INTO library (uuid, user_id, create_time, update_time)
SELECT
    gen_random_uuid(),
    u.uuid,
    u.create_time + INTERVAL '1 day',
    CURRENT_TIMESTAMP
FROM users u
WHERE NOT EXISTS (
    SELECT 1 FROM library l WHERE l.user_id = u.uuid
    );